ALTER TABLE weather_data
    ADD COLUMN IF NOT EXISTS apparent_temperature DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS wind_chill DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS heat_index DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS visibility DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS wind_direction DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS snowfall_amount DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS ice_accumulation DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS probability_of_thunder DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS ceiling_height DOUBLE PRECISION;
